/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login"),
  chat: () => import("@/views/chat/index.vue"),
  component: () => import("@/views/component/index.vue"),
  "file-manager": () => import("@/views/file-manager/index.vue"),
  home: () => import("@/views/home/index.vue"),
  markdownedit: () => import("@/views/markdownEdit/index.vue"),
  mobile: () => import("@/views/mobile/index.vue"),
  "upload-v2-demo": () => import("@/views/upload-v2-demo/index"),
  upload: () => import("@/views/upload/index.vue"),
  utils: () => import("@/views/utils/index.vue"),
  monitoring: () => import("@/views/monitoring/index")
};
