/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'chat',
    path: '/chat',
    component: 'layout.base$view.chat',
    meta: {
      title: 'chat',
      i18nKey: 'route.chat',
      icon: 'mdi:chat',
      order: 2
    }
  },
  {
    name: 'component',
    path: '/component',
    component: 'layout.base$view.component',
    meta: {
      title: 'component',
      i18nKey: 'route.component'
    }
  },
  {
    name: 'file-manager',
    path: '/file-manager',
    component: 'layout.base$view.file-manager',
    meta: {
      title: 'file-manager',
      i18nKey: 'route.file-manager',
      icon: 'mdi:file-tree'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'markdownedit',
    path: '/markdownedit',
    component: 'layout.base$view.markdownedit',
    meta: {
      title: 'markdownedit',
      i18nKey: 'route.markdownedit',
      icon: 'mdi:markdown',
      order: 2
    }
  },
  {
    name: 'mobile',
    path: '/mobile',
    component: 'layout.base$view.mobile',
    meta: {
      title: 'mobile',
      i18nKey: 'route.mobile'
    }
  },
  {
    name: 'upload',
    path: '/upload',
    component: 'layout.base$view.upload',
    meta: {
      title: 'upload',
      i18nKey: 'route.upload',
      icon: 'mdi:upload'
    }
  },
  {
    name: 'utils',
    path: '/utils',
    component: 'layout.base$view.utils',
    meta: {
      title: 'utils',
      i18nKey: 'route.utils'
    }
  }
];
